on:
  pull_request:
    branches: [master]

jobs:
  only:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -S . -B build -DSBASH64_PHASE_VOCODER_ENABLE_TESTS=1 -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: test
        run: ctest -C Release -V
        working-directory: ./build
