on: workflow_dispatch

jobs:
  only:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: generate build system
        run: |
          cmake -S . -B build -DSBASH64_PHASE_VOCODER_ENABLE_EXAMPLE=1 -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
