name: ctest

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test ${{ matrix.compiler }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [g++, clang++]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: build and install fftw
        run: |
          wget -qO- "http://www.fftw.org/fftw-3.3.8.tar.gz" | tar -xz -C /tmp 
          cd /tmp/fftw*/
          ./configure
          make
          make install
      - uses: actions/checkout@v2
      - name: generate build system
        env:
          CXX: ${{ matrix.compiler }}
        run: cmake -S . -B build -DENABLE_TESTS=1 -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build build
      - name: test
        run: |
          cd build 
          ctest
